# Generated by Django 5.1.7 on 2025-05-29 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='lecture',
        ),
        migrations.CreateModel(
            name='LectureStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lectures', to='lectures.lecture')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lectures.student')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='lecture',
            field=models.ManyToManyField(related_name='students', through='lectures.LectureStudent', to='lectures.lecture'),
        ),
    ]
