# Generated by Django 5.2.1 on 2025-05-29 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='lecture',
            new_name='lectures',
        ),
    ]
