# Generated by Django 5.1.7 on 2025-05-29 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0002_remove_student_lecture_lecturestudent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturestudent',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.lecture'),
        ),
        migrations.AlterField(
            model_name='lecturestudent',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectures.student'),
        ),
    ]
