# Generated by Django 5.1.7 on 2025-05-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lectures', '0003_alter_lecturestudent_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturestudent',
            old_name='code',
            new_name='lecture',
        ),
        migrations.RenameField(
            model_name='lecturestudent',
            old_name='student_id',
            new_name='student',
        ),
    ]
