# Generated by Django 5.2.1 on 2025-05-29 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("lecture", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="lecture",
        ),
        migrations.CreateModel(
            name="LectureStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                (
                    "Student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lecture.student",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lecture.lecture",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="student",
            name="lecture",
            field=models.ManyToManyField(
                related_name="students",
                through="lecture.LectureStudent",
                to="lecture.lecture",
            ),
        ),
    ]
