# Generated by Django 5.2.1 on 2025-05-29 02:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("lecture", "0002_remove_student_lecture_lecturestudent_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lecturestudent",
            old_name="Student",
            new_name="student",
        ),
    ]
